# Generated by Django 4.2 on 2023-05-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_kitchenrequest_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenrequest',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Связь'),
        ),
    ]
